### ISSUE TITLE
Get-WDACCodeIntegrityEvent does not return anything

### ISSUE THREAD

**Issue by lduczmal** [mattifestation/WDACTools#6]
Hi,
I have test machine with DeviceGuard enabled and working, and with one policy in audit mode implemented. In Microsoft-Windows-CodeIntegrity/Operational event log I see some 3033, 3089 and other events, but one I run Get-WDACCodeIntegrityEvent in my PS window it returns nothing. What is wrong? Could you help?
Best regards

**Comment by mattifestation** [comment]
Hey, @lduczmal. `Get-WDACCodeIntegrityEvent` parse 3076 (audit) and 3077 (enforce) events which are related to WDAC enforcement. Only if you supply the `-SignerInformation` switch will 3089 (signer information) events be parsed and correlated with the corresponding 3076/3077 event.

3033 events are not explicitly related to WDAC enforcement. They surface most often when a module attempts to load in a protected process that does not meet the appropriate signing requirements.

Please confirm that you have 3076 or 3077 events in the `Microsoft-Windows-CodeIntegrity/Operational` event log. If you do, `Get-WDACCodeIntegrityEvent` will parse them. If you have those events but `Get-WDACCodeIntegrityEvent` isn't parsing them though, please provide as much detail as possible and I can try to help. Thank you.

**Comment by lduczmal** [comment]
Thank you for very quick answer - lack of 3076 and 3077 events was cause that I got nothing from `Get-WDACCodeIntegrityEvent`. Apart from already mentioned event ids I have only 3004, 3084 and 3010.
Is it possible to extend `Get-WDACCodeIntegrityEvent` to work also with 3033/3034 and 3004?
Best regards
LukiD

**Comment by mattifestation** [comment]
At one point I considered writing a parser for 3033 events but ultimately decided not to since the events are not explicitly related to WDAC enforcement.
